// Generated by CoffeeScript 1.3.1
(function() {
  var InstantSearch;

  InstantSearch = {
    running: false,
    request: null,
    url: "/search/search",
    old_search_term: "",
    init: function() {
      $("input#q").keyup(function() {
        InstantSearch.search($(this).val());
        return false;
      });
      return $("form#instant_search").submit(function(event) {
        InstantSearch.search($("input#q").val());
        return event.preventDefault();
      });
    },
    search: function(search_term) {
      if (InstantSearch.running) {
        InstantSearch.request.abort();
        InstantSearch.running = false;
      }
      if (search_term === "") {
        InstantSearch.show_results("", "");
        return this.old_search_term = search_term;
      } else {
        if (search_term !== this.old_search_term && search_term.length >= 3) {
          this.old_search_term = search_term;
          return this.request = $.getJSON(this.url, {
            q: search_term
          }, function(data) {
            return InstantSearch.show_results(data, search_term);
          });
        }
      }
    },
    show_results: function(data, search_term) {
      var data_length, list;
      InstantSearch.running = false;
      data_length = data.length;
      $("#results").empty();
      if (data_length > 0) {
        list = $("<ul></ul>");
        $.each(data, function(i, item) {
          return list.append("<li><a href=\"" + item.url + "?q=" + search_term + "\">" + item.title + "</li>");
        });
        return $("#results").append(list);
      }
    }
  };

  $(document).ready(function() {
    var term, _i, _len, _ref, _results;
    InstantSearch.init();
    if (window.location.search) {
      _ref = $.url(window.location.search).param('q').split(' ');
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        term = _ref[_i];
        _results.push($('article').highlight(term));
      }
      return _results;
    }
  });

}).call(this);
